#!/usr/bin/python
# MIT License
# 2015 www.codeChick.it Buk! Buk!
import imp

deployment_script_path = os.path.abspath(os.path.join(os.sep, 'home','gitdev','git-res', 'deployment.py'))

dep = imp.load_source('deployment', deployment_script_path)
deployment = dep.Deployment()

# Deployment's overrides here


deployment.pre_deploy()